#version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sudoku-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/mydatabase
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=example
    ports:
#     TODO: Change to "8080" when ready for production
      - "8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sudoku-frontend
    ports:
      - "8085:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mariadb:11
    container_name: sudoku-db
    environment:
      - MARIADB_ROOT_PASSWORD=example
      - MARIADB_DATABASE=mydatabase
    ports:
#     TODO: Change to "3306" when ready for production
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
